/**
 * Development seed. Run with `npx prisma db seed` from the repo root.
 *
 * Idempotent: every write is an `upsert` on the row's natural key, so running
 * it twice changes nothing and running it against a partially seeded database
 * fills in what is missing. It never deletes anything.
 *
 * `DATABASE_URL` comes from the environment. `prisma db seed` loads the root
 * `.env` through `prisma.config.ts` and this script inherits it; when running
 * the script directly, export the variable yourself.
 *
 * ## Two things it is careful about
 *
 * 1. **It refuses a database that is not disposable.** The check is
 *    {@link assertDisposableDatabase}, on the connection string rather than on
 *    `NODE_ENV`, and it prints the host it is about to write to. This script
 *    creates accounts and hands out feed credentials; nothing but discipline
 *    used to stop it doing that to a staging database.
 * 2. **It never overwrites an `icsToken` that already exists.** The token is
 *    minted once, in the `create` branch, and the `update` branch does not
 *    mention it. Re-seeding after a developer has regenerated theirs through
 *    the UI would otherwise re-validate a feed URL they deliberately revoked —
 *    which is the exact property `schema.prisma` documents on the column.
 *    `role` and `active` stay in `update` on purpose: those are the seed's to
 *    assert, and `apps/lets-park/web-e2e` depends on `inactive@example.com` being
 *    inactive at the start of every run.
 */

import { createPrismaClient } from '../lib/create-prisma-client';
import { assertDisposableDatabase } from '../lib/disposable-database';
import {
  RESERVATION_LIMIT_SETTINGS_ID,
  RESERVATION_WINDOW_SETTINGS_ID,
  SEED_PARKING_SPOTS,
  SEED_RESERVATION_LIMIT_SETTINGS,
  SEED_RESERVATION_WINDOW_SETTINGS,
  SEED_USERS,
} from '../lib/seed-data';
import { seedUserUpsertArgs } from '../lib/seed-writes';

/**
 * Where the printed feed URLs point. The seed has no validated environment of
 * its own (`apps/lets-park/api/src/env.ts` owns that), so this is a plain fallback to the
 * API's documented development port rather than a second source of truth.
 */
function apiBaseUrl(): string {
  return process.env['NEXT_PUBLIC_API_URL'] ?? 'http://localhost:3000/api';
}

async function main(): Promise<void> {
  const target = assertDisposableDatabase(process.env['DATABASE_URL']);
  console.log(
    `Seeding database "${target.database}" on ${target.host}` +
      (target.overridden ? ' (LETS_PARK_ALLOW_DESTRUCTIVE_RESET=1).' : '.')
  );

  const prisma = createPrismaClient({ connectionString: target.url });

  try {
    for (const spot of SEED_PARKING_SPOTS) {
      await prisma.parkingSpot.upsert({
        where: { label: spot.label },
        update: { group: spot.group, active: spot.active },
        create: spot,
      });
    }
    console.log(`Seeded ${SEED_PARKING_SPOTS.length} parking spots.`);

    const feedUrls: string[] = [];

    for (const user of SEED_USERS) {
      const { preferredParkingSpotLabel } = user;
      const preferredParkingSpotId =
        preferredParkingSpotLabel === null
          ? null
          : (
              await prisma.parkingSpot.findUniqueOrThrow({
                where: { label: preferredParkingSpotLabel },
                select: { id: true },
              })
            ).id;

      // `seed-writes.ts` owns the shape, and `seed-writes.spec.ts` asserts the
      // one property that matters about it: `icsToken` is in `create` and never
      // in `update`, so a token minted on a previous run — or regenerated by the
      // account holder — survives a re-seed.
      const { where, update, create } = seedUserUpsertArgs(user, preferredParkingSpotId);
      const row = await prisma.user.upsert({
        where,
        update,
        create,
        select: { email: true, icsToken: true },
      });

      feedUrls.push(`  ${row.email}  ${apiBaseUrl()}/calendar/${row.icsToken}.ics`);
    }
    console.log(`Seeded ${SEED_USERS.length} users.`);

    // Printed rather than committed. These are live credentials — anyone
    // holding one reads that account's whole calendar — so they exist only in
    // the database and in this terminal, and only for a database
    // `assertDisposableDatabase` has already agreed is disposable.
    console.log('Personal ICS feed URLs (secret; regenerate in Nastavení to revoke):');
    for (const line of feedUrls) {
      console.log(line);
    }

    // The init migration already inserted this row; the upsert restores the
    // documented defaults if someone changed them while poking around.
    await prisma.reservationWindowSettings.upsert({
      where: { id: RESERVATION_WINDOW_SETTINGS_ID },
      update: SEED_RESERVATION_WINDOW_SETTINGS,
      create: { id: RESERVATION_WINDOW_SETTINGS_ID, ...SEED_RESERVATION_WINDOW_SETTINGS },
    });
    console.log('Seeded reservation window settings.');

    // Same arrangement as the window settings above: the migration already
    // inserted this row, and the upsert restores the documented default if an
    // admin changed the cap while poking around.
    await prisma.reservationLimitSettings.upsert({
      where: { id: RESERVATION_LIMIT_SETTINGS_ID },
      update: SEED_RESERVATION_LIMIT_SETTINGS,
      create: { id: RESERVATION_LIMIT_SETTINGS_ID, ...SEED_RESERVATION_LIMIT_SETTINGS },
    });
    console.log('Seeded reservation limit settings.');

    // No reservations or waitlist entries are seeded: they are date-bound and
    // would be in the past by the time anyone runs this. Create them in the UI.
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
